# Configuration script to Travis-CI
language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - pypy
    - pypy3
matrix:
    include:
        - python: "3.6"
          env: TOXENV=flake8,docs
        - python: "3.7"
          dist: xenial
          sudo: true
install:
    - pip install tox tox-travis coveralls
script:
    - tox
after_success:
    - coveralls
notifications:
    email: false
