# Configuration script to Travis-CI
language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - pypy
    - pypy3
matrix:
    include:
        - python: "2.7"
          env: TOXENV=flake8,docs
        - python: "3.7"
          dist: xenial
          sudo: true
install:
    - pip install coveralls coverage
    - pip install zope.testrunner
    - pip install -U -e .[test]
script:
    - coverage run -m zope.testrunner --test-path=src -v
after_success:
    - coveralls
notifications:
    email: false
